update: 좋아요 버튼 완성
B-05-Final-Project/HereNow pull request #11
Opened 2024-07-29 12:09 UTC by Maestrossa

- 좋아요 버튼 로직 (optimistic update 사용) 완성
- 지역상세페이지 tanstack query 사용하여 refactor 완료.

2024-07-29 12:27 UTC, junghyunwoo02 commented on package-lock.json
리액트 쿼리가 그새 업데이트 됐나보네요 충돌 예감이...

2024-07-29 12:35 UTC, junghyunwoo02 requested changes

2024-07-29 12:35 UTC, junghyunwoo02 commented on src/components/LocalDetails/NearbyPlaces.tsx
> +            {nearbyPlaces.map((place: any) => (
any로 타입 지정은 안될 것 같습니다...

2024-07-29 12:36 UTC, junghyunwoo02 commented on src/hooks/local-details.ts
> +export const useAdditionalData = (id: number, typeId: string, options: any) => {
여기도 any네요

2024-07-30 01:50 UTC, leeseayoung submitted a review, later dismissed
확인했습니다

2024-07-30 02:03 UTC, SecretCandy submitted a review, later dismissed

2024-07-30 02:05 UTC, junghyunwoo02 approved these changes
ㄱㄱ

2024-07-30 02:06 UTC, SecretCandy approved these changes

2024-07-30 02:06 UTC, merged