마이페이지(로그인 기능) 완료
B-05-Final-Project/HereNow pull request #14
Opened 2024-07-30 07:21 UTC by leeseayoung

- 마이페이지 UI,기능 완료
- 로그인 기능(이메일 로그인 기능)완료

2024-07-30 07:27 UTC, junghyunwoo02 requested changes

2024-07-30 07:27 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +  const [posts, setPosts] = useState<any[]>([]);
any로 타입 지정은 안됩니다.

2024-07-30 07:28 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +  const [isEditing, setIsEditing] = useState(false);
제네릭으로 타입 지정이 되어있는 useState도 있고 그렇지 않은 것들도 있는 것 같은데 이유가 있나요?

2024-07-30 07:30 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +          console.error('에러', profileError.message);
에러가 발생했는지 콘솔창에만 나오게 하지 말고 사용자도 바로 알 수 있게 토스트 메세지로 알려주는 게 좋아보이네요

2024-07-30 07:30 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +          console.error('Error fetching posts:', postsError.message);
여기도 에러 처리 부탁드립니다

2024-07-30 07:31 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +      console.error('Error uploading file:', error.message);
여기도 사용자가 무엇 때문에 에러가 발생했는 지 알 수 있게 토스트 메세지로도 보여주세요

2024-07-30 07:32 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +        console.error('에러', updateError.message);
여기도

2024-07-30 07:32 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +        toast.success('프로필 수정이 완료되었습니다.');
특별히 토스트 메세지를 커스터마이징 하신게 아니라면 통일성을 위해 제가 만들어둔 showToast로 사용해주시면 좋을 것 같습니다

2024-07-30 07:34 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +          <img
넥스트에선 Image 컴포넌트 사용 부탁드립니다

2024-07-30 07:35 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +                <svg
가독성을 위해 SVG는 컴포넌트로 분리해서 사용하는 건 어떤가요

2024-07-30 07:35 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +            <svg
여기도 SVG 동일

2024-07-30 07:37 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +          <div>{/* 작성한 게시글 */}</div>
falsy한 값이 주석 처리 되어 있는데 이러면 삼항연산자를 쓰는 이유가 없어보이네요. 나중에 바꾸게 되더라도 지금은 삼항연산자를 쓰지 않도록 바꿔주세요

2024-07-30 07:41 UTC, junghyunwoo02 commented on src/app/sign-in/page.tsx
> +    showToast('success', '로그인 성공');
여기 혹시 토스트메시지가 보이기도 전에 홈 화면으로 가지나요? 그런 부분이 우려되네요

2024-07-30 07:43 UTC, junghyunwoo02 commented on src/app/sign-in/page.tsx
> +      showToast('error', error.message);
그냥 토스트메세지로 error.message를 보여주는 것보다 error.message는 console.error로 보여주고 
사용자에게 뜨는 메세지에는 한글로 적어주는 게 좋을 것 같습니다. ex) 로그인에 실패했습니다 이런 식으로요

2024-07-30 07:43 UTC, junghyunwoo02 commented on src/app/sign-in/page.tsx
> +      showToast('error', error.message);
여기도 동일

2024-07-30 07:44 UTC, junghyunwoo02 commented on src/zustand/useAuthStore.ts
> +interface AuthStore {
저희 type으로만 타입 지정하기로 통일했던 걸로 기억하는데 type으로 수정해주세요

2024-07-30 07:45 UTC, junghyunwoo02 commented on src/zustand/useAuthStore.ts
> +  clearUser: () => void;
clearUser는 로그아웃하는 기능인가요?

2024-07-31 03:20 UTC, Maestrossa submitted a review, later dismissed
수고하셨습니다

2024-07-31 04:55 UTC, show1486 approved these changes

2024-07-31 05:13 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +          showToast('error', `프로 파일 에러`);
프로필 정보를 가져오는 중에 오류가 발생했습니다. 라고 하면 좋을 것 같습니다

2024-07-31 05:15 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +        showToast('error', `유저 불러오기 에러`);
유저 정보를 불러오는 중에 오류가 발생했습니다 라고 하면 좋을 것 같습니다

2024-07-31 05:19 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +      } = await supabase.auth.getUser();
35번째 줄과 여기71번째 줄도 supabase.auth.getUser();를 하는 데 똑같은 코드를 사용하신 이유가 궁금합니다

2024-07-31 05:23 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +          showToast('error', `작성,찜한 글 에러`);
여기는 작성, 찜한 글이 없으면 에러를 보여주는 부분 같은데 'error'를 'info'로 바꾸고 '작성하거나 찜한 글이 없습니다.'
라고 바꾸는 게 좋을 것 같네요 아니면 글이 없으면 작성한 게시글이 없어요라고 이미 알려주고 있으니까 콘솔창에만 띄우던가 아예 이 에러를 사용자에게 안 보여줘도 될 것 같네요

2024-07-31 05:24 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +        console.log(error.message);
여기 콘솔 로그 지워주세요

2024-07-31 05:25 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +        showToast('error', `슈퍼베이스 에러`);
슈퍼베이스 에러라는 멘트보다 다른 걸 쓰는 게 좋을 것 같은데 만약 35번 째 줄에 있는 코드와 같은 기능이라면 그냥 코드 자체를 지워도 될 것 같습니다

2024-07-31 05:26 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +      showToast('error', `이미지 업로드 에러`);
이미지 업로드 중 오류가 발생했습니다. 라고 하는게 좋아보이네요

2024-07-31 05:29 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +      showToast('error', `프로파일 업로드 에러`);
함수이름이 handleUpdate인 거 보니 프로필 업데이트 하는 함수 같은데 여기도 토스트메세지를 프로필 수정 중에 오류가 발생했습니다. 라고 하는 게 좋아보이네요

2024-07-31 05:30 UTC, junghyunwoo02 commented on src/app/mypage/[id]/page.tsx
> +        showToast('error', `프로필 파일 업로드 에러`);
여기도 기능에 맞게 메세지 자세하게 작성해주세요

2024-07-31 05:31 UTC, junghyunwoo02 requested changes
새로 코멘트 남겨드렸습니다

2024-08-01 01:18 UTC, Maestrossa submitted a review, later dismissed
수고하셨습니다!

2024-08-01 01:19 UTC, junghyunwoo02 submitted a review, later dismissed

2024-08-01 01:23 UTC, junghyunwoo02 approved these changes

2024-08-01 01:24 UTC, Maestrossa approved these changes

2024-08-01 01:24 UTC, merged