Feature/mainpage
B-05-Final-Project/HereNow pull request #15
Opened 2024-07-30 10:10 UTC by show1486

header,footer / 메인페이지/검색결과페이지 피드제외 기능 올리겠습니다.

2024-07-30 10:14 UTC, SecretCandy submitted a review, later dismissed
넵 확인했습니다 수고하셨습니다

2024-07-30 11:01 UTC, Maestrossa reviewed
수고하셨습니다.
중요하게 고쳐주셔야할게 몇군데 있어보입니다~!

2024-07-30 12:12 UTC, junghyunwoo02 requested changes

2024-07-30 12:15 UTC, junghyunwoo02 commented on src/components/MainPage/Header/Header.tsx
> +type propsdata = {
타입이름은 파스칼케이스 맞춰주세요

2024-07-30 12:16 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalItem.tsx
> +type itemtypeprops = {
여기도 파스칼 케이스 맞춰주세요

2024-07-30 12:17 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +  coords: {
coords는 오타인가요?

2024-07-30 12:19 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +export default function LocalSection() {
코드 컨벤션 맞춰주세요 export default는 코드 최하단에 있어야 합니다.

2024-07-30 12:20 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +  const getLocationdata = async (latitude: number, longitude: number) => {
카멜케이스 맞춰서 알파벳 D 대문자로 바꿔주세요

2024-07-30 12:20 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +      console.log(items);
콘솔 로그 지워주세요

2024-07-30 12:21 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +        `https://apis.data.go.kr/B551011/KorService1/locationBasedList1?MobileOS=ETC&numOfRows=2&MobileApp=new&_type=JSON&mapX=${longitude}&mapY=${latitude}&radius=20000&contentTypeId=12&serviceKey=$
api호출 하는 부분은 라우트 핸들러 사용해주시는 게 좋을 것 같네요 엔드포인트만 클라이언트에서 호출하는 게 좋을 것 같습니다

2024-07-30 12:25 UTC, junghyunwoo02 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +    alert(`Error (${error.code}): ${error.message}`);
alert 대신 showToast 사용해주세요 그리고 에러 메세지를 사용자 입장에서 무슨 상황인지 알 수 있게 써주시고 error.code, message 같은 건 콘솔 에러나 로그로 처리해주세요

2024-07-30 12:26 UTC, junghyunwoo02 commented on src/components/MainPage/Skeleton/Skeleton.tsx
> +type props = {
무슨 프롭스인지 명시해주셔야 할 것 같고 타입 이름은 파스칼 케이스로 작성해주세요

2024-07-30 12:28 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchFeed.tsx
> +export default function SearchFeed() {
여기도 코드 컨벤션 맞춰주세요

2024-07-30 12:30 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchForm.tsx
> +export default function SearchForm({ setIsbg }: SetIsBgProps) {
여기도 코드 컨벤션 맞춰주세요

2024-07-30 12:31 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchForm.tsx
> +  const [storgedata, setStorgedata] = useState<string[]>(() => {
카멜케이스 써주세요

2024-07-30 12:32 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchForm.tsx
> +  const originaldata = storgedata.filter(
여기도 카멜케이스

2024-07-30 12:34 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchForm.tsx
> +    console.log('click');
콘솔 로그 지워주세요

2024-07-30 12:34 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchForm.tsx
> +    const filtereddata = storgedata.filter((data) => data !== i);
카멜케이스로 써주세요

2024-07-30 12:37 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchForm.tsx
> +      {originaldata.map((i, index) => {
i를 정확하게 명시해주면 좋을 것 같습니다

2024-07-30 12:40 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchItem.tsx
> +type SearchItemprops = {
파스칼케이스로 작성해주세요

2024-07-30 12:40 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchItem.tsx
> +  searchdata: searchedtype[];
이것도

2024-07-30 12:42 UTC, junghyunwoo02 commented on src/components/MainPage/api/searchApi.ts
이건 차라리 커스텀 훅으로 빼시는 게 좋아보입니다

2024-07-30 12:42 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchItem.tsx
> +  const [resdata, setResdata] = useState<searchedtype[]>([]);
여기 있는 상태들도 카멜케이스로 맞춰주세요

2024-07-30 12:43 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchItem.tsx
> +      const resarrs = [res, res2, res3, res4];
여기도 카멜케이스로 해주시고 api 응답값을 배열에 넣으신 이유가 있나요?

2024-07-30 12:45 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchItem.tsx
> +    const firstdata = resdatas[0];
인덱스 값을 인자로 받는 하나의 함수로 만들면 좋을 것 같아요

똑같은 로직이 반복되는 게 좋지 않아보여요

2024-07-30 12:48 UTC, junghyunwoo02 commented on src/components/MainPage/search/SearchItem.tsx
> +  function SkeletonItem() {
스켈레톤 카드를 컴포넌트로 분리하는 건 어떨까요

2024-07-30 12:55 UTC, junghyunwoo02 commented on src/types/maintype.ts
카멜케이스로 파일이름 작성해주세요

2024-07-30 12:55 UTC, junghyunwoo02 commented on src/types/maintype.ts
> +export type itemtype = {
여기는 파스칼케이스

2024-07-30 12:56 UTC, junghyunwoo02 commented on src/types/maintype.ts
> +// addr1: '서울특별시 중구 세종대로 110 서울특별시청';
주석 지워주세요

2024-07-30 12:58 UTC, junghyunwoo02 commented on src/types/search.ts
> +    firstimage: 'string';
타입에 따옴표를 쓰신 이유가 있나요?

2024-07-30 14:58 UTC, show1486 commented on src/components/MainPage/Main/section/LocalSection.tsx
> +  coords: {
오타아닙니당 ㅠㅠ

2024-07-31 03:24 UTC, junghyunwoo02 commented on src/app/page.tsx
> +      <div className="flex flex-col items-center justify-center max-w-[400px] mx-auto">
레이아웃에서 max-w-[400px] mx-auto 주고 있어서 이 부분만 지우시면 될 것 같습니다

2024-07-31 03:26 UTC, junghyunwoo02 commented on src/components/Footer/Footer.tsx
> +    <footer className="max-w-[400px] mx-auto w-full fixed bottom-0 z-10 ">
여기도 레이아웃에 이미 적용되고 있습니다!

2024-07-31 03:29 UTC, junghyunwoo02 commented on src/components/Layoutheader/Layoutheader.tsx
> +    <header className="fixed z-10 right-0 max-w-[400px] w-full left-0 mx-auto">
max-w-[400px] mx-auto 여기도 이 부분 지워주세요

2024-07-31 03:30 UTC, junghyunwoo02 commented on src/components/MainPage/Header/Header.tsx
> +type PropsData = {
(무슨)DataProps 이런 식으로 작성하시면 좋을 것 같습니다

2024-07-31 03:33 UTC, junghyunwoo02 commented on src/types/maintype.ts
여기가 아직 안바뀐 것 같네요

2024-07-31 03:35 UTC, junghyunwoo02 requested changes
코멘트 추가로 남겨드렸습니다

2024-07-31 03:55 UTC, show1486 commented on src/components/Footer/Footer.tsx
> +    <footer className="max-w-[400px] mx-auto w-full fixed bottom-0 z-10 ">
여기는 줘야됩니다..ㅠㅠ

2024-07-31 03:57 UTC, show1486 commented on src/components/Layoutheader/Layoutheader.tsx
> +    <header className="fixed z-10 right-0 max-w-[400px] w-full left-0 mx-auto">
여기도 줘야됩니다..ㅠㅠ

2024-08-01 01:33 UTC, junghyunwoo02 approved these changes

2024-08-01 01:35 UTC, leeseayoung approved these changes
수고하셨습니다

2024-08-01 01:35 UTC, Maestrossa approved these changes
수고하셨습니다.

2024-08-01 01:36 UTC, merged