add: 좋아요버튼 컴포넌트 & 공유하기 버튼 기본로직 추가
B-05-Final-Project/HereNow pull request #3
Opened 2024-07-22 11:35 UTC by Maestrossa

- 좋아요 버튼 아이콘 & 기본로직 컴포넌트 추가
- 공유하기 기능 추가

2024-07-22 11:38 UTC, SecretCandy approved these changes

2024-07-22 11:38 UTC, SecretCandy commented on src/components/LocalDetails/like.tsx
> +  const [liked, setLiked] = useState(false);
혹시 여유가 되신다면 Like 부분만 화살표 함수 --> 함수 표현식으로 바꿔주시면 감사드리겠습니다!! 수고하셨습니다

2024-07-22 11:38 UTC, junghyunwoo02 approved these changes
좋습니다 수정 사항도 다 반영된 거 같고 머지하면 될 것 같아요.

2024-07-22 11:39 UTC, SecretCandy reviewed
아!! 그리고 충돌이 있는 것 같네요

2024-07-22 11:39 UTC, junghyunwoo02 commented on src/components/LocalDetails/like.tsx
> +  const [liked, setLiked] = useState(false);
코드 컨벤션 지켜주세요!!!!

2024-07-22 12:44 UTC, junghyunwoo02 requested changes

2024-07-22 12:44 UTC, junghyunwoo02 commented on src/components/LocalDetails/like.tsx
> +      console.error('복사 실패', err);
복사에 실패하면 토스트알림을 뜨게 하는 것도 좋을 것 같네요

2024-07-22 13:20 UTC, junghyunwoo02 submitted a review, later dismissed
고생하셨습니다!

2024-07-23 02:17 UTC, junghyunwoo02 approved these changes

2024-07-23 02:26 UTC, SecretCandy approved these changes

2024-07-23 02:30 UTC, merged