Feature/sign-up
B-05-Final-Project/HereNow pull request #5
Opened 2024-07-23 10:55 UTC by leeseayoung

회원가입 기능 개발 완료

2024-07-23 11:01 UTC, junghyunwoo02 requested changes

2024-07-23 11:01 UTC, junghyunwoo02 commented on src/app/sign-in/page.tsx
> +function SignINPage() {
IN으로 되어 있는데 In으로 바꿔주셔야 될 것 같습니다

2024-07-23 11:04 UTC, junghyunwoo02 commented on src/app/sign-up/page.tsx
> +  const onBlurNickname = (e: FocusEvent<HTMLInputElement>) => {
onBlurNickname이라는 이름에서 Blur가 흐릿해지다, 모호해지다 라는 뜻으로 알고 있는데 여기선 무슨 뜻인가요?

2024-07-23 11:06 UTC, junghyunwoo02 commented on src/app/sign-up/page.tsx
> +  const onChangepasswordConfirm = (e: ChangeEvent<HTMLInputElement>) => {
p 대문자로 바꿔주세요!

2024-07-23 11:08 UTC, junghyunwoo02 commented on src/app/sign-up/page.tsx
> +      showToast('error', error.message);
여기는 error.message를 보여주는 것 보다 에러 처리를 명확하게 사용자가 무슨 상황인지 알 수 있게 해주면 좋을 것 같습니다. ex) 회원가입 도중 오류가 발생했습니다.

2024-07-23 11:41 UTC, junghyunwoo02 submitted a review, later dismissed
고생하셨습니다!

2024-07-24 00:06 UTC, Maestrossa requested changes
리뷰단것 확인부탁드립니다!

2024-07-24 03:33 UTC, SecretCandy approved these changes
수고하셨습니다~~!!

2024-07-24 07:15 UTC, junghyunwoo02 approved these changes

2024-07-24 07:23 UTC, Maestrossa approved these changes
수고하셨습니다!

2024-07-24 10:34 UTC, merged